### PR TITLE
better pointers, better logic, papa john's

### PR DESCRIPTION
**Pull request by just-ero**
added pointers for which we actually know the offsets thanks to dumping the unreal engine objects. reduce amount of position checks.

### CODE REVIEW

**Comment by just-ero** [comment]
Requesting @geerky42 for review.

**Comment by geerky42** [comment]
Hey, thanks for taking your time to improve it!

Unfortunately, I did a couple of runs and I got couple of unexpected splits right when I returned to the game from the menu. I am not sure what happened exactly; I am novice at ASL, sorry.

Other than that, everything else seems to work. Thanks for bringing back the reset feature!

I'd say hold on merging until we figure out this bug.

**Comment by just-ero** [comment]
How can this occur? Doesn't the timer reset upon entering the main menu? How come the timer is running in the menu?

**Comment by geerky42** [comment]
No, it only resets when I click "New Game." We don't really want reset upon entering the menu because menu strat is a thing now ("Return to Main Menu" then "Resume").

**Pull request merged**
